<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('LayoutAbout'); ?>

    <!-- Header -->
 
        <div class="container">
            <div class="row"><
                <h3 class="lead"><b><i>REGRAS</i></b>                </h3>
                <p class="text-muted">
            Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.
        </p>
                <h3 class="lead"><b><i>REGRAS</i></b>                </h3>
                <p class="text-muted">
            Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.
        </p>
                <h3 class="lead"><b><i>REGRAS</i></b>                </h3>
                <p class="text-muted">
            Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.
        </p>
                <h3 class="lead"><b><i>REGRAS</i></b>                </h3>
                <p class="text-muted">
            Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.
        </p>
            </div>
<?php Layout::includeLayout('footer')?>