<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                

            </div>
        </div>
    </header>
    <!-- /Header -->


    <!-- Intro -->
    <div class="container text-center">
                
    </div>
    <!-- /Intro-->

    </div>


    <div class="container text-center">

        <h2>TeSP Programação de Sistemas de Informação</h2>
        <h3>Programação Web - Servidor</h3>
        <br>
        <p class="text-muted">
            Made by Gonçalo Amaro, Joel Runa and Pedro Neves
        </p>
      
        <img width="25%" height="25%" src="<?=Asset::image('iplogo.jpg')?>"><h4 class="thin">Departamento de Engenharia Informática - Escola Superior de Tecnologia e Gestão - Instituto Politécnico de Leiria</h4>

    </div>

<?php Layout::includeLayout('footer')?>