<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


	//session_start();
	
?><br></br>
<?php
	$action = 'new';
	if(isset($_GET['action'])) $action = $_GET['action'];
	
	if($action == 'new') {
		$_SESSION['game'] = new Blackjack();
		$_SESSION['game']->addCard('Player');
		$_SESSION['game']->addCard('Dealer');
	} 
	
	if($action == 'hit') {
		if($_SESSION['game']->Scores['Player'] < 21) {
			$_SESSION['game']->addCard('Player', 1);	
			if($_SESSION['game']->Scores['Player'] > 21) $_SESSION['game']->playBank();
		}
	}
	
	if($action == 'stand') {
		$_SESSION['game']->playBank();
	}
	echo "Player Cards:<br>";
	foreach($_SESSION['game']->Cards['Player'] as $card) 
		echo "<img src='/card{$card['Suit']}{$card['Face']}.png'>";
	echo "<br>Player Score: ".$_SESSION['game']->Scores['Player'];
	
	echo "<br><br>Dealer Cards:<br>";
	foreach($_SESSION['game']->Cards['Dealer'] as $card)?>
		<img src='<?=Asset::image("cardClubs2.png")?>'>
	<?php
	echo "<br>Dealer Score: ".$_SESSION['game']->Scores['Dealer'];
	
	// Options
	if($_SESSION['game']->Scores['Player'] < 21) echo "<br><a href='?action=hit'>[Hit]</a>";
	echo "<br><a href='?action=stand'>[Stand]</a><br><a href='?action=new'>[New]</a>";
	
	if($_SESSION['game']->GameEnd == 1)
	echo "<br>Game Result: ".$_SESSION['game']->getResult();

?>