<?php 
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('LayoutHeader')?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BlackJack</title>
</head>
<body>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<div id="menu" style="text-align: center;margin-right: auto;margin-left: auto">
   <button><a href="index" class="Fade">Sair</a></button><br></br>
   <button><a href="blackjack" class="Fade">Começar Jogo</a></button><br></br>
</div>

<div id="content">

<div id="content-center">

</body>



<?php Layout::includeLayout('LayoutFooter'); ?>