<?php

	ini_set('arg_separator.output', '&amp;');
	if(isset($_SESSION['game'])){
		$CardsArray = $_SESSION['game'];

		//Check size
		$size = sizeof($CardsArray);

		//Draw Card
		//Draw Random Card For Plauer
		$rand_keys = array_push($CardsArray, 1);
		$rand_card = $CardsArray[$rand_keys];

		//Remove from array
		unset($CardsArray[$rand_keys]);

		if($size == "47"){
			//Draw Card
			$rand_card = "$rand_card";
			$_SESSION['rand_card'] = $rand_card;
		}

		echo"
		<img src=\"http://localhost/BlackJack/public/img/Cards/cardClubs2.png\" width=\"180\" height=\"232\" />
		";

	}

?>