<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

    <!-- Header -->
    
    <!-- /Header -->


    <!-- Intro -->
    
    <!-- /Intro-->

        <!-- Highlights - jumbotron -->
    <!-- /row  -->

       
    <!-- /Highlights -->

    <!-- container -->
    

	<!-- /container -->

<?php Layout::includeLayout('footer')?>