<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

    <!-- Header -->
    
    <!-- /Header -->


    <!-- Intro -->
    
    <!-- /Intro-->

        <!-- Highlights - jumbotron -->
    <!-- /row  -->
    

    <!-- /Highlights -->

    <!-- container -->
    
<div class="container text-center">
                
    </div>
    <!-- /Intro-->

    </div>


    <div class="container text-center">
<br></br><br></br>
        <h2>Jogo</h2>
        <h3>Programação Web - Servidor</h3>
        <br>
        <p class="text-muted">
           
        </p>
      
        <img width="25%" height="25%" src="<?=Asset::image('iplogo.jpg')?>"><h4 class="thin">Departamento de Engenharia Informática - Escola Superior de Tecnologia e Gestão - Instituto Politécnico de Leiria</h4>
    </div>
	<!-- /container -->

<?php Layout::includeLayout('footer')?>