0<style>
.footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
}

.footer2 {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
}
</style>
<footer id="footer" class="top-space">

<div class="footer2">
    <div class="container">
        <div class="row">
            
                <div class="widget-body">
                    <p class="text-center">
                   Elaborado por Gonçalo Amaro, Joel Runa, Pedro Neves 2017/2018
                    </p>
                
            </div>

        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>