<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                       

            

            </div> <!-- /row of widgets -->
        </div>
    </div>

<div class="footer2">
    <div class="container">
        <div class="row">

            <div class="col-md-6 widget">
                <div class="widget-body">
                    <p class="text-right">
                            By Gonçalo Amaro, Joel Runa, Pedro Neves. <br>
                    </p>
                </div>
            </div>

        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>