<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header') //faz include do layout/header na página.
?>
<?php $users = Data::get('users') ?>
<?php ErrMgr::attach($users) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">New user</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							<form method="post" action="<?=Url::toRoute('home/store')?>">
								<div class="top-margin">
									<label>Name <span class="text-danger">*</span></label>
									<input type="text" value="<?=$users->name?>" name="name" class="form-control" placeholder="Enter Username">
                                    <?= ErrMgr::bind('name') ?>

								</div>
								
								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">New</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->