<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header') //faz include do layout/header na página.
?>
<?php $users = Data::get('users') ?>
<?php ErrMgr::attach($users) ?>

<!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead" style="color:#FF8C00" ><b>Blackjack Game</b><br><br></h1>
                
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/start')?>">PLAY NOW</a></p>
                <p class="small" style="color:black">Project By:<i> Carlos Franco / Nuno Nunes / Rui Silva</i></p>
            </div>
        </div>
    </header>
     <!--/Header -->


<!-- Intro -->
<html>
<body>
        <!--login -->
        <div class="container">
            <h2> Login </h2>
            <!--Faz o POST dos inputs em baixo e ao clicar no submeter leva os dados para verificação no Route::home/login -->
            <form method="post" action="<?= URL::toRoute('home/login')?>">
                <div>
                    <label>Username </label> <br>
                    <input type="text" value="<?=$users->username?>" class="form-control" name="username">
                </div>
                <div>
                    <label>Password </label> <br>
                    <input type="password" value="<?=$users->password?>" class="form-control" name="password">
                </div>
                <div>
                    <br> <button> Login </button>
                </div>
            </form>
        </div>

        <!-- <h1 class="container"> or </h1> -->

        <!--Register -->
        <div class="container">
            <h2> Register </h2>
            <!--Faz o POST dos inputs em baixo e ao clicar no submeter leva os dados para o Route::home/store -->
            <form method="post" action="<?= URL::toRoute('home/register')?>"> 
                <div>
                    <label>Full Name </label> <br>
                    <input type="text" value="<?=$users->name?>" class="form-control" name="name">
                    <?= ErrMgr::bind('name') ?>
                </div>
                <div>
                    <label>Date of birth </label> <br>
                    <input type="date" value="<?=$users->birth?>" class="form-control" name="birth">
                </div>
                <div>
                    <label>Email </label> <br>
                    <input type="text" value="<?=$users->email?>" class="form-control" name="email">
                </div>
                <div>
                    <label>Username </label> <br>
                    <input type="text" value="<?=$users->username?>" class="form-control" name="username">
                </div>
                <div>
                    <label>Password </label> <br>
                    <input type="password" value="<?=$users->password?>" class="form-control" name="password">
                </div>
                <div>
                <br> <button> Register </button>
                </div>
            </form>
        </div>
</body>
</html>