<?php 
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') //faz include do layout/header na página.
?>
<?php $users = Data::get('users') ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">View users</h1>
				</header>
				
				<div class="row">
                <div class="col-sm-12">
                <table class="table table-striped">
                <thead><th><h3>Id</h3></th><th><h3>Name</h3></th><th><h3>Email</h3></th><th><h3>Username</h3></th></thead>
                <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                    <td><?=$user->id?></td>
                    <td><?=$user->name?></td>
                    <td><?=$user->email?></td>
                    <td><?=$user->username?></td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

            </div>
            <div class="col-sm-6">
                <h3>Create a new user</h3>
                <p>
                    <a href="<?=Url::toRoute('users/create')?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->