<?php 
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Footer;
Layout::includeLayout('indexheader');

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BlackJack</title>
</head>
<body>
	<br>
</br>
<br>
</br>
<br>
</br>
<?php
//Array with all the cards
$cards = array("\public\img\cardClubs2");
$size = sizeof($cards);
echo "$size";
?>
</body>




<?php Layout::includeLayout('footer'); ?>


