	<?php 
	use ArmoredCore\WebObjects\Post;
	use ArmoredCore\WebObjects\Layout;
	use ArmoredCore\WebObjects\Footer;
	Layout::includeLayout('indexheader');

	?>	
<html>
<head>
<style type="text/css">
	body {
		margin:0px;
	}
</style>
</head>
<body>
    <h2 style='text-align:center;'>Blackjack</h2>
	<div align='center' style="background-color:beige; padding:5px; width:300px; margin:auto;">
    <div style="text-decoration:underline; font-weight:bold;">Your Hand is:</div><br/>
   
</div>
<?php Layout::includeLayout('footer'); ?>
</body>
</html>