<?php
include_once("\model\Game.php");
// Establish defaults
$gameOver = 0;
$game = new Game();		// Create a new deck and start a new game
/**clear all session variables if user plays again**/
if (isset($_GET['again'])) {
}
session_start();
if (!isset($_GET['hit']) && !isset($_GET['stand'])) {
    /**initial deal**/
    $userHand[0] = $game->dealCard();
    $dealerHand[0] = $game->dealCard();
    $userHand[1] = $game->dealCard();
    $dealerHand[1] = $game->dealCard();
    $_SESSION['userHand'] = $userHand;
    $_SESSION['dealerHand'] = $dealerHand;
	$_SESSION['dHandValue'] = $game->getHandValue($_SESSION['dealerHand']);
} else if (isset($_GET['hit'])) {
    $_SESSION['userHand'][sizeof($_SESSION['userHand'])] = $game->dealCard();
    $_SESSION['userValue'] = $game->getHandValue($_SESSION['userHand']);
	$_SESSION['dHandValue'] = $game->getHandValue($_SESSION['dealerHand']);
	$_SESSION['uHandValue'] = $game->getHandValue($_SESSION['userHand']);
	// Auto-stand if at 21
    if ($_SESSION['userValue'] == 21)
		header("Location: index.php?stand=stand");
	// Check if, by hitting, the game has ended
	$gameOver = $game->winCheck($_SESSION['userValue'], $_SESSION['dHandValue'], 0);
} else if (isset($_GET['stand'])) {
    while ($_SESSION['dHandValue'] < 17) {
        $_SESSION['dealerHand'][sizeof($_SESSION['dealerHand'])] = $game->dealCard();
        $_SESSION['dHandValue'] = $game->getHandValue($_SESSION['dealerHand']);
		$_SESSION['uHandValue'] = $game->getHandValue($_SESSION['userHand']);		
    }
	$gameOver = $game->winCheck($_SESSION['uHandValue'], $_SESSION['dHandValue'], 1);
}
?>
}
?>